<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_1_2_3</name>
   <tag></tag>
   <elementGuidId>14cb2ef9-721b-48a7-a02f-d3ddc22f1ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>frame >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>3215b555-ac2f-423c-b86f-6c8787e9d33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>frame_4.html</value>
      <webElementGuid>0f770b92-8c46-4ed8-9917-1f1ed672aa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frame[3]</value>
      <webElementGuid>5211c77b-b82c-4d1a-bf6b-c70297630c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[3]</value>
      <webElementGuid>f1632053-7609-494a-8c0a-2a63333c8a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'frame_4.html']</value>
      <webElementGuid>4981ac17-46b8-4feb-af47-f718c98eb624</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
