<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_1</name>
   <tag></tag>
   <elementGuidId>fd60b5aa-e5cd-41e6-84fa-547af31b069b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frameset > frameset > frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frameset/frameset/frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>frame >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>0db57ae6-b3c5-4bbb-880c-e539b43f293b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>frame_2.html</value>
      <webElementGuid>45822afd-dbcd-4d13-b458-4699f9b294d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frame[1]</value>
      <webElementGuid>a9e38191-96c8-4309-95c8-473055ee6bb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset/frameset/frame</value>
      <webElementGuid>b93b6b12-dda4-417a-be6f-1e55eb06be30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'frame_2.html']</value>
      <webElementGuid>e1f88513-0bfe-4982-bec4-c34bf6941ee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
