<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Berikutnya</name>
   <tag></tag>
   <elementGuidId>75f43f50-6cea-493c-8ef0-9b4a4a50e798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.uArJ5e.UQuaGc.YhQJj.zo8FOc.ctEux.qs41qe.M9Bg4d > span.l4V7wb.Fxmcue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mG61Hd']/div[2]/div/div[3]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Berikutnya&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ea862c23-1a91-4d32-b417-d70d4c3d41c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l4V7wb Fxmcue</value>
      <webElementGuid>285a3ddf-126e-404a-af6f-526ea4aec674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berikutnya</value>
      <webElementGuid>bb743324-1936-45da-b848-e51a24fb7680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mG61Hd&quot;)/div[@class=&quot;RH5hzf RLS9Fe&quot;]/div[@class=&quot;lrKTG&quot;]/div[@class=&quot;ThHDze&quot;]/div[@class=&quot;DE3NNc CekdCb&quot;]/div[@class=&quot;lRwqcd&quot;]/div[@class=&quot;uArJ5e UQuaGc YhQJj zo8FOc ctEux qs41qe M9Bg4d&quot;]/span[@class=&quot;l4V7wb Fxmcue&quot;]</value>
      <webElementGuid>12beb2de-ed0d-444d-9c6f-c80d6155cc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frames - Web Automation Test/iframe_Loading</value>
      <webElementGuid>4f97bde7-f391-4754-b274-e4949a2033b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mG61Hd']/div[2]/div/div[3]/div/div/div/span</value>
      <webElementGuid>4b06dfa9-b6f4-49bc-a476-52e051528601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Well, now I know :-)'])[1]/following::span[1]</value>
      <webElementGuid>576694f3-6510-45e7-9652-f8e25e40d99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::span[2]</value>
      <webElementGuid>dcd9b29d-f8e5-4c9e-8c3a-c197752c24a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kosongkan formulir'])[1]/preceding::span[2]</value>
      <webElementGuid>a9194a2a-3835-4113-9bf5-58c0bd01c7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/span</value>
      <webElementGuid>fa05a2e4-5326-4271-9868-4966689792ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Berikutnya' or . = 'Berikutnya')]</value>
      <webElementGuid>e8a74dc5-91bf-4ed3-b350-acdc0abeb110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
