<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EvaluateResult.Type</name>
   <tag></tag>
   <elementGuidId>ae255146-8512-4eb8-92f3-ff3560be0092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.type-name-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='nested-class-summary']/div[2]/div[5]/code/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nested-class-summary >> internal:role=link[name=&quot;EvaluateResult.Type&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c472624-b0fb-41ba-83be-0a0d602fe4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>EvaluateResult.Type.html</value>
      <webElementGuid>b708c83e-b22a-45f8-a764-487e0a8c46a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>type-name-link</value>
      <webElementGuid>635f62d2-e2cc-4b82-be0d-464b167ab638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>enum class in org.openqa.selenium.bidi.script</value>
      <webElementGuid>16b68a50-339f-4b8d-96f1-4d7ea1bb4b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EvaluateResult.Type</value>
      <webElementGuid>c2144b98-0613-4bde-b6d6-b099abfbdc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nested-class-summary&quot;)/div[@class=&quot;summary-table three-column-summary&quot;]/div[@class=&quot;col-second even-row-color&quot;]/code[1]/a[@class=&quot;type-name-link&quot;]</value>
      <webElementGuid>8c355588-2f2b-46d6-9f45-03e3d04456fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='nested-class-summary']/div[2]/div[5]/code/a</value>
      <webElementGuid>e257fa42-53f8-43bf-a64b-c51fdb8d329d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EvaluateResult.Type')]</value>
      <webElementGuid>084ad8e3-eab5-4ed0-b2ac-0affefcbdf31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::a[1]</value>
      <webElementGuid>77963c8a-767a-4d3f-9001-1bf34b6bab59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method Summary'])[1]/preceding::a[1]</value>
      <webElementGuid>2b3568f0-bec2-4bdb-a829-52179b041a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Methods'])[1]/preceding::a[1]</value>
      <webElementGuid>59a252cf-f137-40aa-a14f-e9e4afe4c350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EvaluateResult.Type']/parent::*</value>
      <webElementGuid>7b0e2576-143a-448a-a3aa-9d624ad562c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'EvaluateResult.Type.html')]</value>
      <webElementGuid>c304481a-a883-42c9-bf53-6d2fef38a7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/code/a</value>
      <webElementGuid>7fa3f440-e636-4811-bcfa-1cac68446225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'EvaluateResult.Type.html' and @title = 'enum class in org.openqa.selenium.bidi.script' and (text() = 'EvaluateResult.Type' or . = 'EvaluateResult.Type')]</value>
      <webElementGuid>85d40c1f-d46f-48c8-a6b4-cfd6a9202e35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
