<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EvaluateResult.Type</name>
   <tag></tag>
   <elementGuidId>415272dc-8456-4e99-8794-375a7060049a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.extends-implements > a[title=&quot;enum class in org.openqa.selenium.bidi.script&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='class-description']/div/span[3]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span >> internal:has-text=&quot;extends Enum&lt;EvaluateResult.Type>&quot;i >> internal:attr=[title=&quot;enum class in org.openqa.selenium.bidi.script&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df2479b5-0e58-43a1-bc6c-7626d7973362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>EvaluateResult.Type.html</value>
      <webElementGuid>abaa4d44-da7a-401c-8325-2962bb01cd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>enum class in org.openqa.selenium.bidi.script</value>
      <webElementGuid>e1d75b5e-88d3-4bc4-adc8-4127c06e9927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EvaluateResult.Type</value>
      <webElementGuid>301a157b-6f29-442a-b58d-25c5ea0db05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-description&quot;)/div[@class=&quot;type-signature&quot;]/span[@class=&quot;extends-implements&quot;]/a[2]</value>
      <webElementGuid>99242d3a-9d12-4f58-8833-4ab6dce9b34b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='class-description']/div/span[3]/a[2]</value>
      <webElementGuid>3355f112-18f6-4af1-8a39-2a2ad19c7bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'EvaluateResult.Type')])[3]</value>
      <webElementGuid>00536e6d-2de0-4593-8ec4-9480b7765e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enum'])[1]/following::a[1]</value>
      <webElementGuid>c2f172d6-0f43-4191-8f49-b18c3230f4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nested Class Summary'])[1]/preceding::a[1]</value>
      <webElementGuid>d7965030-8c9d-4778-9611-d2abc9a76ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'EvaluateResult.Type.html')])[4]</value>
      <webElementGuid>be52d557-a9f5-461b-8e02-446372e7b16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a[2]</value>
      <webElementGuid>a0d33835-ef25-4ffe-bca0-dad8b300482f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'EvaluateResult.Type.html' and @title = 'enum class in org.openqa.selenium.bidi.script' and (text() = 'EvaluateResult.Type' or . = 'EvaluateResult.Type')]</value>
      <webElementGuid>c04c8863-2497-46bd-a4ff-7aebb434ea95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
