<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EvaluateResult</name>
   <tag></tag>
   <elementGuidId>5e1f86a2-bc7f-4af2-9a74-47c64c39fea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;interface in org.openqa.selenium.bidi.script&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='class-summary.tabpanel']/div/div[15]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;EvaluateResult&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba0d934f-edc3-437e-b176-47e508ce1eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>EvaluateResult.html</value>
      <webElementGuid>e25e216a-fcea-45a1-9a00-c0c80a24d618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>interface in org.openqa.selenium.bidi.script</value>
      <webElementGuid>1aeb581a-6215-4156-acfb-616fac7a3f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EvaluateResult</value>
      <webElementGuid>dd55c49d-d586-469f-86f6-7646e0c55220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary.tabpanel&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first even-row-color class-summary class-summary-tab1&quot;]/a[1]</value>
      <webElementGuid>9625059e-68d3-47b2-8e41-1104065399c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary.tabpanel']/div/div[15]/a</value>
      <webElementGuid>e7fadd1c-16cb-49f2-b767-d9ea97d30bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EvaluateResult')]</value>
      <webElementGuid>ed75bc11-1dab-4b4a-b5e6-15975e1cf939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EvaluateParameters'])[1]/following::a[1]</value>
      <webElementGuid>27cd308e-2c31-462a-800c-dc1948551336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DateLocalValue'])[1]/following::a[2]</value>
      <webElementGuid>9628b540-0d88-4a85-8a07-d129f4fd9e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EvaluateResult.Type'])[1]/preceding::a[1]</value>
      <webElementGuid>5b667947-09bc-4561-8444-f5c56f1831e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EvaluateResultExceptionValue'])[1]/preceding::a[2]</value>
      <webElementGuid>af2adcbb-7e05-4d79-8b0a-ab026fe8900a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EvaluateResult']/parent::*</value>
      <webElementGuid>49acc4a1-cf99-4a12-96f0-a3d9565e1717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'EvaluateResult.html')]</value>
      <webElementGuid>e4516b0e-04e5-494c-8ed2-3ec970eceea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/a</value>
      <webElementGuid>22e35971-ab06-4974-b204-7e675cb7d27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'EvaluateResult.html' and @title = 'interface in org.openqa.selenium.bidi.script' and (text() = 'EvaluateResult' or . = 'EvaluateResult')]</value>
      <webElementGuid>c23b5f9a-5f99-4cca-a4d2-b9602f0fa4ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
